
vault:
  image: hashicorp/vault:1.15.0
  replicas: 2
  serviceType: LoadBalancer
  storagePath: /vault/data
  ingress:
    enabled: true
    host: vault.cloudmasa.app

postgres:
  image: postgres:15
  replicas: 2 
  serviceType: LoadBalancer
  storagePath: /var/lib/postgresql/data
  username: vault_user
  password: vault_password
  database: vault_db
  ingress:
    enabled: true
    host: postgres.cloudmasa.app
