apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: {{ .Values.vault.replicas }}
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: {{ .Values.vault.image }}
          env:
            - name: VAULT_ADDR
              value: "http://0.0.0.0:8200"
          ports:
            - containerPort: 8200
          volumeMounts:
            - name: vault-config
              mountPath: /etc/vault.d
            - name: vault-storage
              mountPath: {{ .Values.vault.storagePath }}
      volumes:
        - name: vault-config
          configMap:
            name: vault-config
        - name: vault-storage
          persistentVolumeClaim:
            claimName: vault-pvc
