apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-agent-injector
  labels:
    app.kubernetes.io/name: vault-agent-injector
    app.kubernetes.io/instance: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault-agent-injector
      app.kubernetes.io/instance: vault
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault-agent-injector
        app.kubernetes.io/instance: vault
      annotations:
        vault.hashicorp.com/agent-inject: "true"
    spec:
      serviceAccountName: vault-agent-injector
      containers:
        - name: vault-agent-injector
          image: hashicorp/vault-k8s:1.0.0
          args:
            - agent-inject
            - -log-level=debug
          env:
            - name: AGENT_INJECT_IMAGE
              value: "hashicorp/vault:1.15.0"
            - name: AGENT_INJECT_VAULT_ADDR
              value: "http://vault:8200"
            - name: AGENT_INJECT_VAULT_AUTH_PATH
              value: "auth/kubernetes"
            - name: AGENT_INJECT_VAULT_ROLE
              value: "vault-agent-injector"
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
            requests:
              cpu: "250m"
              memory: "64Mi"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-agent-injector
  labels:
    app.kubernetes.io/name: vault-agent-injector
    app.kubernetes.io/instance: vault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-agent-injector
  labels:
    app.kubernetes.io/name: vault-agent-injector
    app.kubernetes.io/instance: vault
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "patch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["get", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-agent-injector
  labels:
    app.kubernetes.io/name: vault-agent-injector
    app.kubernetes.io/instance: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-agent-injector
subjects:
  - kind: ServiceAccount
    name: vault-agent-injector
    namespace: default
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: vault-agent-injector
  labels:
    app.kubernetes.io/name: vault-agent-injector
    app.kubernetes.io/instance: vault
webhooks:
  - name: vault.hashicorp.com
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    clientConfig:
      service:
        name: vault-agent-injector
        namespace: default
        path: "/mutate"
      caBundle: ""
    namespaceSelector:
      matchLabels:
        vault-injection: enabled
